### ISSUE TITLE
Breach of Github T&Cs?

### ISSUE THREAD

**Issue by hughesjs** [easimon/maximize-build-space#13]
Hi,

Just wondering if any sort of advice has been sought regarding whether or not this breaches the Github T&Cs?

I could do with using this action but I'm concerned it may end up getting my account limited/banned.

Cheers,

James

**Comment by easimon** [comment]
I haven't asked -- but why would you think this breaches T&C? 

My warning about "voiding warranty" is more targeting at the facts, that 

- the action just `rm -rf`s preinstalled software without any consistency checks, and remounts storage in a way that could interfere with the VM setup ... and this in turn might or might not break your workflow (or even runner internals). 
- the action somewhat depends on the Azure VM type that is used by Github. Any change on their side might break the action.

As I understand it, each run on GH actions receives a fresh virtual machine that is terminated afterwards. So even if you totally break the VM, it should not affect other builds or customers, just your current build. But, I could totally understand that Github support rejects support requests when using this action, because it's just a hack.

**Comment by hughesjs** [comment]
I'm not saying it does, it just *feels* like something that MS would get upset about.

That being said, if you're confident enough of your last statement, then I can't see why there'd be a problem.

**Comment by reavpC6K** [comment]
Barely hollowing out the actions. This leaves behind lots of bloat.
