### ISSUE TITLE
Potentially to revert actions

### ISSUE THREAD

**Issue by felbinger** [easimon/maximize-build-space#17]
Is it somehow possible to revert / change the space distribution after a specific point. I tried to rerun your action (with `root-reserve-mb` and `temp-reserve-mb` set), but unfortunately it doesn't work and I get the error `fallocate: invalid length value specified`. I guess the action isn't made for something like this yet?

https://github.com/os-builds/kali/runs/7927017365

I'm trying to build a iso, which requires a lot of space. The github actions workflow works until I try to upload the iso. I guess that the upload-artifact action requires space on root oder temp fs?

**Comment by easimon** [comment]
I would not know how to achieve that, TBH. That would be equivalent to live resizing partitions (LVM LV+PV) and filesystems. It might be possible, but at the moment it's not implemented. 

That would also be something completely different than the initial process of creating the workspace partition, so calling the maximize-build-space action twice can't work. This is a one-shot action.

There are parameters to control reserve space on the temp and root partition for cases like these. For this to work, you would need to know how much space your build actually needs, and more importantly, how much the upload action requires, and where -- and the given reserve space would then be missing in the workspace partition. 

And, you can use the overprovisioning switch to create the LVM in a "sparse" manner, so it does not take all committed space immediately, but grows on write (but never shrinks again when deleting files). Use with care, since this might lead to surprising failed allocations when the disk is actually full.

This might require a bit of experimentation, but maybe worth a try.

**Comment by felbinger** [comment]
> There are parameters to control reserve space on the temp and root partition for cases like these. For this to work, you would need to know how much space your build actually needs, and more importantly, how much the upload action requires, and where -- and the given reserve space would then be missing in the workspace partition.

I think this can't work, after the build I have 8.2 GB left on the lv. After cleanup (I just keep the iso), I have arround 12 GB on the lv in use, so I belive that the ISO is, 12 gb in total. I will check this with a simple du -h, but due to the fact that I'm building Kali Linux everything this sounds right. 
![image](https://user-images.githubusercontent.com/26925347/185806839-7edcfa33-66d6-4aa5-9ff1-2355a9b48cde.png)

Due to the fact, that I have not enough spare space left (arroudn 10 gb, cause I reserved one gb for both root and temp) I might have some fun with this... Thank you so far. I will try it, when I have some time off...

**Comment by easimon** [comment]
A last thought: I don't know what is required for your build, but the Ubuntu runners come with a lot of software preinstalled... I added three options to remove potentially unnecessary software -- but that's only the three largest I found quickly, but the result is still not particularly "slim". You could try to find other large (and unneeded) directories using rm -rf or apt prior to calling the maximize-build-space action, if you find them.
Might be time-consuming to identify unnecessary large packages, but worth the investigation if it's important enough for you.
