### ISSUE TITLE
are LVM operations required

### ISSUE THREAD

**Issue by sifive-benjamin-morse** [easimon/maximize-build-space#28]
Are the LVM operations required? Would it be possible to just remove the software and skip the LVM step? I only ask because I'm not sure what maximum value I should provide for the `root-reserve-mb` option. Thanks.

**Comment by easimon** [comment]
While it would be possible to just remove the software, the LVM setup merges mostly unused temp disk space with the free space of the main disk, adding about 9 GB available space alone. Since these are different disks on the VM, LVM is required to do the merge.

At the moment, skipping this step is not implemented, and I also don't plan it, TBH. 

Have you just tried the default for root-reserve-mb of 1024 == 1GB? Does it fail for you?

**Comment by easimon** [comment]
sorry for the late answer, maybe you already figured that:

the software removal is really mostly a `rm -rf` on a few directories... you could add that easily directly to your workflow directly and not rely on this action.

For reference: these are the commands used for the packages "known" to the action as `remove-*`: 

```
          echo "Removing unwanted software... "
          if [[ ${{ inputs.remove-dotnet }} == 'true' ]]; then
            sudo rm -rf /usr/share/dotnet
          fi
          if [[ ${{ inputs.remove-android }} == 'true' ]]; then
            sudo rm -rf /usr/local/lib/android
          fi
          if [[ ${{ inputs.remove-haskell }} == 'true' ]]; then
            sudo rm -rf /opt/ghc
          fi
          if [[ ${{ inputs.remove-codeql }} == 'true' ]]; then
            sudo rm -rf /opt/hostedtoolcache/CodeQL
          fi
          if [[ ${{ inputs.remove-docker-images }} == 'true' ]]; then
            sudo docker image prune --all --force
          fi
          echo "... done"
```
