### ISSUE TITLE
Configuring this action to be less aggressive

### ISSUE THREAD

**Issue by Zethson** [easimon/maximize-build-space#4]
Hey,

this is the only action that made our build work, so thank you.
Would it be possible to offer a less aggressive version or configurable version ideally which only deletes some usually never used stuff like the android sdk?

**Comment by easimon** [comment]
Great to hear this hack is really helpful for anybody.

But I am a bit puzzled regarding your question. I think the defaults are quite un-aggressive -- and the action is configurable as well, see https://github.com/easimon/maximize-build-space#inputs for a description, and also the expected space each option gives you.

If that is not configurable enough or still too aggressive, please add more details. 

On the other hand, I think removing only portions of e.g. the Android SDKs is a granularity that is not really maintainable. If you're building for Android, you should keep the SDKs completely, or otherwise remove them entirely. I see little point in an option "in-between".

**Comment by easimon** [comment]
I haven't heard from you in a while, so I will close the issue. Feel free to reopen if necessary.

**Comment by Zethson** [comment]
Sorry, I had been busy. All fine.
