### ISSUE TITLE
temp and root partition swapped

### ISSUE THREAD

**Issue by michabp** [easimon/maximize-build-space#42]
For two weeks or so the root partition and the temp partition has been swapped on around 20% of the runners.

Which results in temp getting bigger and root staying small:
```
/dev/root                     73G   73G  100M 100% /
```

**Comment by easimon** [comment]
Please see https://github.com/easimon/maximize-build-space/issues/39#issuecomment-1935591779

Can this be an explanation for what you see?

The tmpfs you mentioned is not the temp partition, but a ramdisk, mounted to /tmp. The temp disk should be mounted at /mnt.

**Comment by michabp** [comment]
Thank you!

Yes, that's probably it. However, I'm confused on what the fix is. Whatever I specify in `temp-reserve-mb` will end up getting added to `/dev/root`.
But if try to make `temp-reserve-mb` very large it'll throw `fallocate: invalid length value specified`.

**Comment by easimon** [comment]
What are you trying to achieve? The action combines all free space on / and /mnt into an lvm volume, which is then mounted as the workspace directory. The workspace is the place where most build jobs require the most space.

The reserve parameters are to control how much space is *not* consumed by the lvm volume, so you can still add files outside the workspace... E.g. to download docker images, install further packages via apt-get etc.

By increasing the reserve, you decrease the amount available in the workspace folder.

The temp reserve is something you should seldomly need to adjust, since by default nothing (I know of) writes to /mnt.

**Comment by ljmf00-wekaio** [comment]
I'm getting this too: `fallocate: invalid length value specified`.

What I think @michabp is suggesting is: check if `/mnt` mountpoint really exists and do the calculations accordingly, otherwise its inconsistent for both configurations. 
If we reserve space on `/mnt` and `/` but `/mnt` doesn't really exist, the reserve total space should be merged, so that it doesn't underflow/overflow on our situation, which is exactly what is happening right now.

It used to be 20% of the runners but now its almost all runners, from my experience.

**Comment by easimon** [comment]
I added #48, which to my knowledge describes the general situation: provided disk space and layout is fluctuating. 
Closing this.
